services:
  - type: web
    name: horseweight-fastapi
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
